---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/sync-wave: "0"
  name: registry-pull-secret
  namespace: nemo-tfm
spec:
  encryptedData:
    .dockerconfigjson: AgBLm60VpnMUM1NhW8qYNZI5p7wO+yhnHOTei/MkGQ6mJXbs/AgFSBnMCKRDxg9HG9hWcKhuMS4zMhcE4aGE+GieMMSRvmBh3J4BUq+C/fb1c0HDodyCAn6Elbppc87wK2n1BqUaBMbE4THWw+QIW8mO+jUOglh1F2oq01SDzAk/C4x+pBDrOscbkQPWIdIX84PhdoAXmVqYoh9HkjmzBN9Ey5So3BM5sIiIbrigvdTdr9f5VQoCj/0xj3WLETWtMHD+Q4qZpm/q1gZfprEPpg8pNj6wZbcKWEuwUO61rgXnJjjQadWt5BO/+qg2j1fvZypihXFPydeAIWift8MQBCQ3bW+1Eq1kUi+nXjITEnL3sdcQ4MUyT1eGM+KDHRujaKQKjOe4N8XzpXOKH6J7FQxZ3M5qRb/Z2My2Rjwp+dL5DFKNYDj/MEzAw3Litz9PqJafo54sjdEAGujpUMFzBa5CG5uSpFaAzx7QHoa9hyQAWubraGZxFjOc+iF0wCOvIBv5w08hYl9aUoK4q5WA90Wv40tA3kAqDw52WUd4ILI4p2ADByQ/dGJt4tPp0Wqdndal+qk9y6TKQ1voNvWUu598RtKKdLpF4wvwn9Cg3DYgCd/dU5TJ2xoIgWM8SAjevLFF/eP1MAxDYKViC93K9gO/cHKoZsJ+uLw2hGlCWZUH/FD6+f5zYpJ89xk8z9EGqRq6qAtUmQ9KNsxubxoD84hc+JCJXvS8V/4qsLzzeIfK91H7jwm52fgWfFq+Y17OvH2Te4JxRKyqbcBg21t7VgX4AhocZj8txizUZx2ZZhkOy7UmjTNg+5YY7Ksu85Nxsx9sB5DxAjPX6bFWjNDMfjAka+8Q+8s4rkPU6uNZeg4fbsO6boPwzEbebUn2TKSfSWbvBw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: registry-pull-secret
      namespace: nemo-tfm
    type: kubernetes.io/dockerconfigjson
